'use client';

import { Sparkles, Bot, AlertCircle } from 'lucide-react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface GeminiSynthesisProps {
  synthesis: string;
}

export function GeminiSynthesis({ synthesis }: GeminiSynthesisProps) {
  return (
    <Card className="bg-card/60 backdrop-blur border-border/50 p-6 space-y-4">
      <div className="flex flex-wrap items-center justify-between gap-2 pb-3 border-b border-border/50">
        <div className="flex items-center gap-2.5">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-indigo-500/20 to-purple-500/20 flex items-center justify-center text-indigo-400">
            <Sparkles className="w-4.5 h-4.5" />
          </div>
          <div>
            <h3 className="font-display text-lg font-bold text-foreground">
              Gemini Initial Synthesis
            </h3>
            <p className="text-xs text-muted-foreground">
              AI-generated structural analysis based on vision line confidence
            </p>
          </div>
        </div>

        <Badge variant="outline" className="bg-indigo-500/10 text-indigo-400 border-indigo-500/30 text-xs px-2.5 py-1 flex items-center gap-1.5">
          <Bot className="w-3.5 h-3.5" />
          AI Initial Output
        </Badge>
      </div>

      <div className="p-4.5 rounded-xl bg-indigo-950/20 border border-indigo-500/20 space-y-3">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wider text-indigo-400">
          <span>Automated Reading Baseline</span>
          <span className="opacity-40">•</span>
          <span className="text-[11px] text-muted-foreground normal-case font-normal">
            For Palm Specialist Review & Refinement
          </span>
        </div>
        <p className="text-sm leading-relaxed text-slate-200 font-normal whitespace-pre-line">
          {synthesis}
        </p>
      </div>

      <div className="p-3 rounded-lg bg-secondary/30 border border-border/40 text-xs text-muted-foreground flex items-center gap-2">
        <AlertCircle className="w-4 h-4 text-amber-400 shrink-0" />
        <span>
          Note: This synthesis was auto-generated by Gemini 3.6 Flash. Specialist interpretation is required to finalize the reading.
        </span>
      </div>
    </Card>
  );
}
