import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  const searchParams = req.nextUrl.searchParams;
  const readingId = searchParams.get('readingId');

  if (!readingId) {
    return NextResponse.json({ error: 'Reading ID required' }, { status: 400 });
  }

  // Generate a clean, standalone document
  const fileContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Mystica Report - ${readingId}</title>
        <style>
          body { font-family: system-ui, sans-serif; padding: 40px; color: #333; line-height: 1.6; max-width: 800px; margin: 0 auto; }
          h1 { color: #6d28d9; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
          .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
        </style>
      </head>
      <body>
        <h1>Mystica Synthesis Report</h1>
        <p><strong>Archive ID:</strong> ${readingId}</p>
        <p>Your AI analysis has been successfully archived in the Mystica Vault.</p>
        <p><em>To view the full interactive details, lines, and spread analysis, please log in to your secure dashboard.</em></p>
        <div class="footer">Generated by Mystica Intelligence Platform</div>
      </body>
    </html>
  `;

  // Force the browser to download it as a file rather than opening it like a webpage
  return new NextResponse(fileContent, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `attachment; filename="Mystica_Report_${readingId.substring(0, 8)}.html"`,
    },
  });
}